---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-apache-example
  labels:
    app: metrics-apache-example
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9117'   
spec:
  selector:
    matchLabels:
      app: metrics-apache-example
  template:
    metadata:
      labels:
        app: metrics-apache-example
    spec:
      containers:
      - image: tsarlewey/caapacheimage:1
        imagePullPolicy: IfNotPresent
        name: apache
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /bin/apache_exporter
        - --scrape_uri
        - http://status.localhost:80/server-status/?auto
        image: lusotycoon/apache-exporter
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: exporter
        ports:
        - containerPort: 9117
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      hostAliases:
      - hostnames:
        - status.localhost
        ip: 127.0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-apache-example
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9117'  
spec:
  selector:
    app: metrics-apache-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80