---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-nginx-example
  labels:
    app: metrics-nginx-example
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9113'
spec:
  selector:
    matchLabels:
      app: metrics-nginx-example
  template:
    metadata:
      labels:
        app: metrics-nginx-example
    spec:
      containers:
      - image: cube8021/metrics-nginx-example:v0.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      - command:
        - /usr/bin/nginx-prometheus-exporter
        - -nginx.scrape-uri=http://status.localhost:8080/stub_status
        image: nginx/nginx-prometheus-exporter:0.10.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9113
          name: metrics
          protocol: TCP
      hostAliases:
      - hostnames:
        - status.localhost
        ip: 127.0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-nginx-example
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9113'  
spec:
  selector:
    app: metrics-nginx-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80