---
apiVersion: v1
kind: Namespace
metadata:
  name: "hpa-example-simple"
  labels:
    name: "hpa-example-simple"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "hello-world"
  name: hello-world
  namespace: hpa-example-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-world"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
      - image: supporttools/hello-world
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hpa-example-simple
  labels:
    app: "hello-world"
spec:
  selector:
    app: "hello-world"
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world
  namespace: hpa-example-simple
spec:
  maxReplicas: 10
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 10
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: hpa-example-simple
spec:
  replicas: 0
  selector:
    matchLabels:
      app: "load-generator"
  template:
    metadata:
      labels:
        app: "load-generator"
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do wget -O /dev/null -o /dev/null http://hello-world:8080 && echo OK; done
        image: busybox
        name: busybox
