apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: webserver
    image: supporttools/hello-world
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
